onerror {resume}
add wave -divider -height 18;
add wave -position insertpoint CLK_PRD;
add wave -position insertpoint clk_100MHz;
add wave -position insertpoint async_reset;
add wave -position insertpoint error_count;
add wave -position insertpoint test_running;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {Entity Input/Output} M;
add wave -position insertpoint -expand -group {Entity Input/Output} write_M;
add wave -position insertpoint -expand -group {Entity Input/Output} Ki;
add wave -position insertpoint -expand -group {Entity Input/Output} write_Ki;
add wave -position insertpoint -expand -group {Entity Input/Output} i;
add wave -position insertpoint -expand -group {Entity Input/Output} en_v0;
add wave -position insertpoint -expand -group {Entity Input/Output} en_v1;
add wave -position insertpoint -expand -group {Entity Input/Output} en_sum;
add wave -position insertpoint -expand -group {Entity Input/Output} ld_j;
add wave -position insertpoint -expand -group {Entity Input/Output} en_j;
add wave -position insertpoint -expand -group {Entity Input/Output} zj;
add wave -position insertpoint -expand -group {Entity Input/Output} cyclenum;
add wave -position insertpoint -expand -group {Entity Input/Output} enC;
add wave -position insertpoint -expand -group {Entity Input/Output} C;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {Round Keys Mem} duv/inst_key_ram/RAM;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {Key Out} duv/write_Ki;
add wave -position insertpoint -expand -group {Key Out} duv/ram_addr;
add wave -position insertpoint -expand -group {Key Out} duv/key_out;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {V0 Register} duv/write_M;
add wave -position insertpoint -expand -group {V0 Register} duv/en_v0;
add wave -position insertpoint -expand -group {V0 Register} duv/v0_v1_next;
add wave -position insertpoint -expand -group {V0 Register} duv/inst_v0_reg/ld_data_i;
add wave -position insertpoint -expand -group {V0 Register} duv/v0;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {V1 Register} duv/write_M;
add wave -position insertpoint -expand -group {V1 Register} duv/en_v1;
add wave -position insertpoint -expand -group {V1 Register} duv/v0_v1_next;
add wave -position insertpoint -expand -group {V1 Register} duv/inst_v1_reg/ld_data_i;
add wave -position insertpoint -expand -group {V1 Register} duv/v1;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {SUM Register} duv/write_M;
add wave -position insertpoint -expand -group {SUM Register} duv/en_sum;
add wave -position insertpoint -expand -group {SUM Register} duv/sum_r_next;
add wave -position insertpoint -expand -group {SUM Register} duv/inst_sum_reg/ld_data_i;
add wave -position insertpoint -expand -group {SUM Register} duv/sum_r_reg;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {SUM Next Add} duv/sum_r_reg;
add wave -position insertpoint -expand -group {SUM Next Add} duv/y;
add wave -position insertpoint -expand -group {SUM Next Add} duv/sum_r_next;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {W00 OR W11 Add} duv/key_out;
add wave -position insertpoint -expand -group {W00 OR W11 Add} duv/sum_r_reg;
add wave -position insertpoint -expand -group {W00 OR W11 Add} duv/w01_w11;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {Sft L 4 R 5 Add} duv/inst_shift_xor/x;
add wave -position insertpoint -expand -group {Sft L 4 R 5 Add} duv/inst_shift_xor/y;
add wave -position insertpoint -expand -group {Sft L 4 R 5 Add} duv/shift_add;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {W00 OR W10 Add} duv/v0_mux_v1;
add wave -position insertpoint -expand -group {W00 OR W10 Add} duv/shift_add;
add wave -position insertpoint -expand -group {W00 OR W10 Add} duv/w00_w10;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {V0V1 Next Add} duv/t0_t1;
add wave -position insertpoint -expand -group {V0V1 Next Add} duv/v1_mux_v0;
add wave -position insertpoint -expand -group {V0V1 Next Add} duv/v0_v1_next;
add wave -divider -height 18;
add wave -position insertpoint -expand -group {J Counter} duv/inst_j_count/srst_i;
add wave -position insertpoint -expand -group {J Counter} duv/en_j;
add wave -position insertpoint -expand -group {J Counter} duv/ld_j;
add wave -position insertpoint -expand -group {J Counter} duv/inst_j_count/count_o;
add wave -position insertpoint -expand -group {J Counter} duv/zj;
add wave -position insertpoint -expand -group {J Counter} duv/*;
add wave -position insertpoint -expand -group {J Counter} duv/inst_xtea_datapath/inst_j_count/*;

run -all;